import { OCR_ALEVEL_BIOLOGY_SPECIFICATION, OCR_ALEVEL_MCQ_RULES, OCR_ALEVEL_P1_OUTCOMES } from './ocr-alevel-biology-scope.ts';

export const OCR_ALEVEL_P2_SAM_URL = 'https://www.ocr.org.uk/Images/171738-unit-h420-02-biological-diversity-sample-assessment-materials.pdf';
export const OCR_ALEVEL_P2_TOPICS = ['Foundations in biology', 'Biodiversity, evolution and disease', 'Genetics, evolution and ecosystems'] as const;

/** Original summaries of H420 v4.1 Modules 2, 4 and 6. Module 1 skills are
 * embedded in the tasks. This is a reviewed outcome pool, not a question bank. */
export const OCR_ALEVEL_P2_OUTCOMES: Record<string, {topic: number; text: string}> = {
  ...Object.fromEntries(Object.entries(OCR_ALEVEL_P1_OUTCOMES).filter(([ref]) => ref.startsWith('2.'))),
  '4.1.1': {topic:1, text:'Pathogen types and transmission; plant and animal defences, phagocytosis, specific cellular/humoral immunity, primary/secondary responses, vaccination, medicines, antibiotic resistance and disease prevention.'},
  '4.2.1': {topic:1, text:'Habitat, species and genetic biodiversity; representative sampling, species richness/evenness, Simpson index, genetic polymorphism, threats and conservation in situ/ex situ.'},
  '4.2.2': {topic:1, text:'Classification and binomial names, three domains, phylogeny and molecular evidence, adaptations, natural selection, evolution and variation; interpret comparative evidence.'},
  '6.1.1': {topic:2, text:'Gene mutations and protein effects; transcriptional control including lac operon and general transcription factors, RNA processing, protein activation, homeobox/Hox genes, mitosis and apoptosis in development.'},
  '6.1.2': {topic:2, text:'Genetic/environmental variation, meiosis, monogenic/dihybrid inheritance, multiple alleles, codominance, sex linkage, linkage/epistasis, chi-squared analysis, genetic drift, bottlenecks, Hardy-Weinberg, speciation and artificial selection.'},
  '6.1.3': {topic:2, text:'DNA sequencing, genome comparison, bioinformatics, DNA profiling, PCR, electrophoresis, vectors/restriction enzymes/ligase, genetic engineering and ethical issues, somatic/germ-line gene therapy; no detailed high-throughput sequencing recall.'},
  '6.2.1': {topic:2, text:'Natural/artificial plant and animal clones, cuttings, micropropagation, embryo splitting and SCNT; microorganisms in food/industrial biotechnology, aseptic culture, batch/continuous fermentation, microbial growth and immobilised enzymes.'},
  '6.3.1': {topic:2, text:'Ecosystems and trophic levels, biomass/energy transfer, recycling including nitrogen cycle, succession, practical sampling and distribution/abundance evidence.'},
  '6.3.2': {topic:2, text:'Population sizes, competition, predator-prey relationships, sustainable resource management and conservation; sampling, population estimation and evaluation of environmental evidence.'},
};

export const OCR_ALEVEL_P2_RULES = `OCR A-LEVEL BIOLOGY A H420/02 Biological diversity, specification ${OCR_ALEVEL_BIOLOGY_SPECIFICATION}. Untiered full A-level, not AS H020, GCSE J247/J257 or Biology B H422.
Assess Modules 1, 2, 4 and 6. Link knowledge across these modules: nucleic acids/protein synthesis to gene control, meiosis to inheritance, membranes/enzymes to immunity and biotechnology, variation to biodiversity/evolution. Module 1 practical and mathematical skills are embedded. All components include synoptic assessment; this does not license Module 3/5-only mechanism recall in Paper 2.
Do not require recall of mammalian ventilation/cardiac control, detailed xylem/phloem transport, nephron/ADH mechanisms, action potentials/synapses, endocrine homeostasis, plant hormone mechanisms, Calvin/Krebs pathways or oxidative phosphorylation. An unfamiliar context can supply all necessary background for an in-scope application, but the task/key must assess the saved Paper 2 outcomes. General ATP, cell membranes and enzymes remain legitimate Module 2 content; general ecological energy transfer remains Module 6 content.
Full mock: 100 marks, 135 minutes, all questions compulsory, Section A Q1-15 fifteen separately scored one-mark MCQs; Section B starts at Q16 and totals 85 marks with structured, calculation, practical/data and extended-response tasks. Parent/part counts and resource/skill allocations are Examly template choices, never official fixed historical counts. Short practice is a labelled Examly development template, not a full official paper. Custom retains saved manual choices.
${OCR_ALEVEL_MCQ_RULES}
Use original biological scenarios and data, not copied OCR questions, figures or passages. Explicit tasks use precise A-level command words such as describe, explain, compare, calculate, suggest, discuss and evaluate, matched to marks and evidence. Give each required resource exactly once with a neutral identifier/caption and necessary givens/units. A calculation needs sufficient data, precision and a consistent private working. Continuous data needs numerical axes. No decorative/mismatched figure, duplicate data, hidden dependency or answer-bearing scaffold.
Inheritance tasks may use incomplete genetic diagrams or tables only when needed; never print assessed offspring genotypes/phenotypes, completed Punnett squares or assessed ratios. Label only supplied structures, never the labels the learner must determine. All matrices, cloze and labelled fields use the shared opt-in response architecture and preserve the original task, resource evidence and maximum marks; do not force a format onto an unsuitable task.
Supply chi-squared formula and critical values/degrees of freedom as needed, Hardy-Weinberg equations when used, Simpson index formula, required statistical formulae and enough inputs. Include appropriate magnification, proportions, sampling/population estimates, growth and statistical interpretation; never infer significance without the test evidence. Skill/AO annotations are drafting targets, not certification of scientific validity or cognitive demand.
Planned six-mark extended responses require private task-specific Level 1 (1-2), Level 2 (3-4), Level 3 (5-6) science descriptors, indicative content and zero for no relevant response. Scientific content selects the best-fit level; coherent communication selects the mark within it. Other written responses use capped points, acceptable alternatives, numerical working and units. No AQA essay rubric, GCSE tier caps, official qualification grade or practical endorsement. Keep private keys, completed answers and worked solutions out of every student-visible field.`;

/** Narrow recall-demand checks complement immutable outcome routing and resource
 * validation. They do not certify arbitrary model-authored scientific content. */
export function ocrAlevelPaper2ContentIssue(text: string): string | null {
  const outside = /\b(?:explain|describe|outline|state|compare)\b[^.?!\n]{0,110}\b(?:Calvin cycle|Krebs cycle|oxidative phosphorylation|chemiosmosis|action potentials?|cholinergic synapses?|saltatory conduction|ultrafiltration|selective reabsorption|ADH (?:action|mechanism)|cardiac cycle|Bohr effect|cohesion[- ]tension|pressure[- ]flow|auxin (?:action|mechanism))\b/i;
  return outside.test(text) ? 'OCR H420/02 task requires Module 3/5-only mechanism recall. Rewrite the complete task and private key within the saved Modules 1, 2, 4 and 6 outcomes; unfamiliar background must be supplied, not assumed.' : null;
}
