// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-subjects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.45.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-subjects.ts
var list_subjects_default = defineTool({
  name: "list_subjects",
  title: "List my subjects",
  description: "List the subjects the signed-in student or tutor has added, with exam board and category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_subjects").select("id, subject_name, custom_name, subject_category, exam_board, curriculum_tag, proficiency_estimate").order("subject_name");
    if (error) throw new ToolError(error.message);
    const subjects = (data ?? []).map((row) => ({
      id: String(row.id),
      name: String(row.custom_name ?? row.subject_name ?? "Untitled subject"),
      category: row.subject_category ?? null,
      examBoard: row.exam_board ?? null,
      level: row.curriculum_tag ?? null,
      proficiency: row.proficiency_estimate ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(subjects, null, 2) }],
      structuredContent: { subjects }
    };
  }
});

// src/lib/mcp/tools/list-exams.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^4.4.3";
var list_exams_default = defineTool2({
  name: "list_exams",
  title: "List my exam papers",
  description: "List the signed-in user's exam papers, newest first, with board, level and status.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("How many papers to return."),
    status: z.string().trim().min(1).optional().describe("Only return papers with this status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("exams").select("id, title, subject_id, status, exam_board, qualification_level, extraction_status, total_questions_extracted, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError2(error.message);
    const exams = (data ?? []).map((row) => ({
      id: String(row.id),
      title: String(row.title ?? "Untitled exam"),
      subject: row.subject_id ?? null,
      status: row.status ?? null,
      examBoard: row.exam_board ?? null,
      level: row.qualification_level ?? null,
      extractionStatus: row.extraction_status ?? null,
      questionCount: row.total_questions_extracted ?? null,
      createdAt: row.created_at ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(exams, null, 2) }],
      structuredContent: { exams }
    };
  }
});

// src/lib/mcp/tools/list-practice-sets.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_practice_sets_default = defineTool3({
  name: "list_practice_sets",
  title: "List my practice quizzes",
  description: "List the signed-in user's practice quiz sets, newest first, with topics and difficulty.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("How many practice sets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("practice_question_sets").select("id, set_name, subject_id, subtopics, question_count, difficulty_level, exam_board, educational_tier, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) throw new ToolError3(error.message);
    const sets = (data ?? []).map((row) => ({
      id: String(row.id),
      name: String(row.set_name ?? "Untitled quiz"),
      subject: row.subject_id ?? null,
      topics: Array.isArray(row.subtopics) ? row.subtopics.map((t) => String(t)) : [],
      questionCount: row.question_count ?? null,
      difficulty: row.difficulty_level ?? null,
      examBoard: row.exam_board ?? null,
      tier: row.educational_tier ?? null,
      status: row.status ?? null,
      createdAt: row.created_at ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(sets, null, 2) }],
      structuredContent: { practiceSets: sets }
    };
  }
});

// src/lib/mcp/tools/list-exam-results.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_exam_results_default = defineTool4({
  name: "list_exam_results",
  title: "List my exam results",
  description: "List the signed-in student's completed exam attempts with score, marks and time taken.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("How many attempts to return."),
    examId: z3.string().uuid().optional().describe("Only return attempts for this exam paper.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, examId }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("exam_submissions").select("id, exam_id, status, total_score, total_marks, time_taken_seconds, submitted_at").order("submitted_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (examId) query = query.eq("exam_id", examId);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    const results = (data ?? []).map((row) => {
      const score = row.total_score === null || row.total_score === void 0 ? null : Number(row.total_score);
      const marks = row.total_marks ?? null;
      return {
        id: String(row.id),
        examId: String(row.exam_id),
        status: row.status ?? null,
        score,
        totalMarks: marks,
        percentage: score !== null && marks ? Math.round(score / marks * 100) : null,
        timeTakenSeconds: row.time_taken_seconds ?? null,
        submittedAt: row.submitted_at ?? null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ynhevbrihlnwzehrfoft";
var mcp_default = defineMcp({
  name: "revise-ai-buddy",
  title: "revise-ai-buddy",
  version: "0.1.0",
  instructions: "Read-only tools for Examly, an AI revision app. Use `list_subjects` for the signed-in user's subjects, `list_exams` for their exam papers, `list_practice_sets` for their practice quizzes, and `list_exam_results` for their scored attempts. All tools act as the signed-in user only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_subjects_default, list_exams_default, list_practice_sets_default, list_exam_results_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
