
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS file_processed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE public.resource_packs ADD COLUMN IF NOT EXISTS file_processed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
