
INSERT INTO subjects (name, slug, category, is_active) VALUES
  ('Accounting', 'accounting', 'humanities', true),
  ('Art & Design', 'art-design', 'other', true),
  ('Biochemistry', 'biochemistry', 'sciences', true),
  ('Biomedical Engineering', 'biomedical-engineering', 'sciences', true),
  ('Business Studies', 'business-studies', 'humanities', true),
  ('Classical Civilisation', 'classical-civilisation', 'humanities', true),
  ('Design & Technology', 'design-technology', 'other', true),
  ('Drama & Theatre', 'drama-theatre', 'other', true),
  ('Economics', 'economics', 'humanities', true),
  ('Electronics', 'electronics', 'sciences', true),
  ('Engineering', 'engineering', 'sciences', true),
  ('Environmental Science', 'environmental-science', 'sciences', true),
  ('Film Studies', 'film-studies', 'other', true),
  ('Food Technology', 'food-technology', 'other', true),
  ('French', 'french', 'languages', true),
  ('Further Mathematics', 'further-mathematics', 'maths', true),
  ('German', 'german', 'languages', true),
  ('Government & Politics', 'government-politics', 'humanities', true),
  ('Health & Social Care', 'health-social-care', 'other', true),
  ('Information Technology', 'information-technology', 'sciences', true),
  ('Italian', 'italian', 'languages', true),
  ('Law', 'law', 'humanities', true),
  ('Mandarin Chinese', 'mandarin-chinese', 'languages', true),
  ('Media Studies', 'media-studies', 'other', true),
  ('Music', 'music', 'other', true),
  ('Music Technology', 'music-technology', 'other', true),
  ('Philosophy', 'philosophy', 'humanities', true),
  ('Photography', 'photography', 'other', true),
  ('Physical Education', 'physical-education', 'other', true),
  ('Psychology', 'psychology', 'sciences', true),
  ('Religious Studies', 'religious-studies', 'humanities', true),
  ('Sociology', 'sociology', 'humanities', true),
  ('Spanish', 'spanish', 'languages', true),
  ('Statistics', 'statistics', 'maths', true),
  ('Urdu', 'urdu', 'languages', true),
  ('Arabic', 'arabic', 'languages', true),
  ('Bengali', 'bengali', 'languages', true),
  ('Polish', 'polish', 'languages', true),
  ('Portuguese', 'portuguese', 'languages', true),
  ('Turkish', 'turkish', 'languages', true),
  ('Japanese', 'japanese', 'languages', true),
  ('Korean', 'korean', 'languages', true),
  ('Latin', 'latin', 'languages', true),
  ('Greek', 'greek', 'languages', true),
  ('Marine Science', 'marine-science', 'sciences', true),
  ('Geology', 'geology', 'sciences', true),
  ('Astronomy', 'astronomy', 'sciences', true),
  ('Forensic Science', 'forensic-science', 'sciences', true),
  ('Criminology', 'criminology', 'humanities', true),
  ('Textiles', 'textiles', 'other', true)
ON CONFLICT DO NOTHING;
